version: '3.8'

services:
  usersservice:
    image: usersservice
    build:
      context: .
      dockerfile: UsersService/Dockerfile
    ports:
      - "5001:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=users-mysql;Database=UsersDb;User=root;Password=yourpassword;"
    depends_on:
      - users-mysql
    networks:
      - mynetwork

  ordersservice:
    image: ordersservice
    build:
      context: .
      dockerfile: OrdersService/Dockerfile
    ports:
      - "5002:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=orders-mysql;Database=OrdersDb;User=root;Password=yourpassword;"
    depends_on:
      - orders-mysql
    networks:
      - mynetwork

  users-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: UsersDb
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  orders-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: OrdersDb
    ports:
      - "3307:3306"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
